### ISSUE TITLE
Clicked buttons change color on following page load

### ISSUE THREAD

**Issue by cyckl** [designbylunar/cupid#85]
On iOS (at the very least), after clicking on a button the text turns blue.

This happens on the page load following the button press but goes away after a refresh or after another button is clicked.

Seems to only affect non-mono buttons in my testing. YMMV.

![image](https://user-images.githubusercontent.com/26363850/128451454-fac65dc8-90b9-45a3-8ad3-56dc7f90b5da.jpeg)

**Comment by cyckl** [comment]
This appears to manifest in the mono and non-disabled button by changing the background to a lighter grey.

![image](https://user-images.githubusercontent.com/26363850/128451638-0fe3da7e-f406-4bc9-8907-caa47a85d273.jpeg)

**Comment by doamatto** [comment]
The top image reflects the issue in #79. 

As for the persistent background from tap on the second button, my best guess is that this occurs based on how accessibility features are handled, but for obvious reasons this isn't the intended behaviour. In theory, however, this could be a non-issue, as the buttons would normally route you elsewhere or reset as they would have actual functionality attached to them (unlike those in the playground).

**Comment by doamatto** [comment]
With a titbit of more investigation, this is due to the button linking to `#` on the page and being an issue with (afaik) how browsers work. Refreshing the page (aka if the page were to reload or go to another page) the button returns to a normal, resolved state. Feel feel to re-open if this persists outside of the playground.
